### PR TITLE
Added hackage badge

### PR DESCRIPTION
**Pull request by JustusAdam**
Added a [shields.io](https://shields.io) badge to the readme with a direct link to the snap package page.

### CODE REVIEW

**Comment by mightybyte** [comment]
Hmmm, this didn't seem to work?

**Comment by JustusAdam** [comment]
It didn't? On my screen it does ...
Ah damn, i made a typo in the hackage url

**Comment by JustusAdam** [comment]
It takes a little while to load sometimes (probably because it isn't cached on the shields.io server)

**Comment by mightybyte** [comment]
Ahh, it's up now.

**Pull request merged**
