### PR TITLE
Bump HUnit

### PR DESCRIPTION
**Pull request by k-bx**
Also add stack support.

Thank you!

### CODE REVIEW

**Comment by hvr** [comment]
Are you aware that the Snap repo is already set up to use gitlinks to sub-repos? Can't Stack reuse those in some way? Otherwise you'd have to manually sync up the stack.yml file everytime we manually update the gitlinks...

**Comment by k-bx** [comment]
@hvr didn't know that, will check. Thank you!

**Comment by k-bx** [comment]
@hvr PR updated. I had to bump heist submodule to latest commit to include aeson version bump.

**Comment by mightybyte** [comment]
@k-bx Thanks for the pull request.  I don't really want to maintain a stack.yaml file because it makes my configuration data less DRY and overly constrains my users to specific versions of dependencies.  As far as I know snap builds just fine with cabal alone and I'm committed to keeping it that way.  If you want to update this pull request to remove the stack.yaml I'll accept it so you can have on-the-record credit for this improvement.  If you don't want to take the time to do that, I'll be happy make these changes myself.

**Comment by k-bx** [comment]
@mightybyte no problem, please go ahead and do the changes, closing this PR.

Regarding "builds just fine with cabal alone" – it doesn't build fine for me at all, neither with global cabal, nor with non-shared or shared sandboxes. Either dependency-hell or damn-long build-times and high space-consumption were hitting me for quite a long time in past in those setups, so for me and others who don't want to get back to "that world" it'd be convenient to just have some stack.yaml on which you can base your build.

**Comment by mightybyte** [comment]
@k-bx Ok, I just pushed those changes.

I also tested a from-scratch build and it works fine.  I did notice that the instructions in the readme had a missing step, so I fixed that.  If you try a clean install with those steps it should work.  The build may take a few minutes, but there are new changes coming to cabal soon that will speed that up.  If the build fails with errors for you, please open another pull request so we can get it fixed.  Thanks for the pull request.

**Comment by k-bx** [comment]
@mightybyte ok, thank you!

**Pull request closed without merging**
