### PR TITLE
bumped aeson

### PR DESCRIPTION
**Pull request by bitemyapp**
I am testing Aeson 0.10. At least this package by itself worked, I don't know if you batch these things or not.
screenshot from 2015-09-18 16 00 16

### CODE REVIEW

**Comment by mightybyte** [comment]
Thanks

**Comment by bitemyapp** [comment]
@mightybyte FYI: https://github.com/bos/aeson/issues/287

Letting you know in case it affects downstream (end-users). I'm going to have to squint at my test suite in Bloodhound before I flip over.

**Comment by mightybyte** [comment]
Thanks for the heads-up.  If the change doesn't affect snap, it seems like the thing to do is just allow the new version and users will have to check their own projects.

**Comment by bitemyapp** [comment]
@mightybyte s'what ahhh figured, just letting you know in case a punter squawks.

**Pull request merged**
